import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Table } from 'lib'
import { ThemeProvider } from 'styled-components';
import { GlobalStyle, theme } from 'assets';

interface LoadingExport extends ComponentMeta<typeof Table> {}
interface LoadingStory extends ComponentStory<typeof Table> {}

export default {
    title: 'Exibição de Dados/Table',
    component: Table,
} as LoadingExport;

const Template: LoadingStory = (args) => <ThemeProvider theme={theme}>
    <GlobalStyle theme={{ ...theme }} />
    <Table
        columns={args.columns}
        rows={args.rows}
        hasSelect={args.hasSelect}
    />
</ThemeProvider>

export const Default = Template.bind({});

Default.args = {
    columns: [
        { title: 'Coluna 1', accessor: 'column1' },
        { title: 'Coluna 2', accessor: 'column2' },
        { title: 'Coluna Muito Muito Grande 3', accessor: 'column3' },
        { title: 'Coluna 4', accessor: 'column4' },
        { title: 'Coluna Muito Grande 5', accessor: 'column5' },
        { title: 'Coluna Grande 6', accessor: 'column6' },
        { title: 'Coluna 7', accessor: 'column7' },
        { title: 'Coluna 8', accessor: 'column8' },
        { title: 'Coluna 9', accessor: 'column9' },
        { title: 'Coluna Final Muito Muito Grande 10', accessor: 'column10' },
    ],
    rows: [
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
        {
            column1: { value: 'Valor 1' },
            column2: { value: 'Valor 2' },
            column3: { value: 'Valor 3' },
            column4: { value: 'Valor 4' },
            column5: { value: 'Valor 5' },
            column6: { value: 'Valor 6' },
            column7: { value: 'Valor 7' },
            column8: { value: 'Valor 8' },
            column9: { value: 'Valor 9' },
            column10: { value: 'Valor 10' },
        },
    ],
    hasSelect: false
}